### PR TITLE
Cocoapods

### PR DESCRIPTION
**Pull request by quanvo87**
Can you regen jazzy again lol

### CODE REVIEW

**Review by dingwilson — DISMISSED** [review]
LGTM

**Comment by dingwilson** [comment]
I kept trying and failing to pull this repo. I was so confused, until I looked closely and saw you accidentally misspelled the branch name 😂

**Comment by quanvo87** [comment]
LOL

**Comment by dingwilson** [comment]
Will squash commits upon merge

**Comment by quanvo87** [comment]
Is the failure cause the test code throws an error?

**Comment by dingwilson** [comment]
Nah that failure is just from [this merge commit](https://github.com/dingwilson/SwiftVideoBackground/pull/43/commits/3991e79a6f48cfc37fa19ecbaff2b606c8d09fe2). I added this check in Danger, so we can squash commits to keep the git history clean. Your code/PR has no issues. Should I remove this check?

edit: nvm I see that travis fails upon Danger throwing an error as well. Can you rebase your commits? That should pass the travis tests.

**Comment by quanvo87** [comment]
I'm not sure. If we keep that check in, what should I do with this PR?

**Comment by dingwilson** [comment]
Rebase or squash, then force push

**Comment by quanvo87** [comment]
I think we can just remove that check.

**Comment by dingwilson** [comment]
After PR #44 is merged, we can trigger a rebuild and the travis tests for this PR should pass.

**Comment by dingwilson** [comment]
Also, @quanvo87 I just realized.. after you review the other PR, you should also add an entry in `CHANGELOG.md` with the relevant changes you've made.

**Review by dingwilson — APPROVED** [review]
LGTM

**Pull request merged**
