### PR TITLE
Updated README with FFmpeg blog post and fixed typos

### LINKED ISSUE #56: short how to on ffmpeg and link in readme

### PR DESCRIPTION
**Pull request by dingwilson**
## What does this PR do?

Updates README with link to FFmpeg blog post

## What issues (if any) are related to this PR? Or why was this change introduced?

Closes #56 

## Checklist

 - [ ] Does this contain code changes?
 - [ ] Does this have tests?
 - [ ] Does this have documentation?
 - [ ] Does this break the public API (Requires major version bump)?
 - [ ] Is this a new feature (Requires minor version bump)?

### CODE REVIEW

**Comment by dingwilson** [comment]
Please lmk if there are any changes I should make to the blog post. 👍

**Review by quanvo87 — COMMENTED** [review]
The blog post looks tight. I think you should make the link more enticing, letting them know there's a nice walk though behind this link. Something like "short how-to here"

**Review by quanvo87 — DISMISSED** [review]

**Comment by quanvo87** [comment]
There is an unrelated error in the README, can you fix before merge?

**Comment by quanvo87** [comment]
Wait I'll try to do it real quick

**Comment by quanvo87** [comment]
Ok I don't know how to do all the git stuff required

**Comment by dingwilson** [comment]
Sure, whats the issue haha

**Comment by quanvo87** [comment]
VideoBackground.shared.play(
    view: view,
    name: "myVideo",
    type: "mp4",
    darkness: 0.25,
    isMuted: false,
    willLoopVideo: true,
    setAudioSessionAmbient: true
)

I think it should be `videoName` and `videoType`

**Comment by dingwilson** [comment]
btw for future reference:

```bash
git fetch origin readme # fetch readme branch
git checkout readme # checkout readme branch
<make changes>
git push origin readme # push changes to GH
git checkout master # checkout master branch
git branch -D readme # delete readme branch
```

**Review by quanvo87 — APPROVED** [review]

**Comment by quanvo87** [comment]
Ahhh thx

**Pull request merged**
